# Generated by Django 4.2.8 on 2024-01-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SwearWords',
        ),
    ]
